
# Generated by Django 4.1.7 on 2023-03-28 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("boardApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="board_tbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("regdate", models.DateTimeField(default=django.utils.timezone.now)),
                ("viewcnt", models.IntegerField(default=0)),
                (
                    "writer",
                    models.ForeignKey(
                        db_column="writer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boardApp.user_tbl",
                    ),
                ),
            ],
        ),
    ]
